### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by itzvenom** [Spencer-Weston/NBA_bet#11]
Hello and thanks for open sourcing your project,

I can seem to make it work, any thoughts?

`C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
Season is up to date; Returning without performing an update.
C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py:2542: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
Traceback (most recent call last):
  File "C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\sergi\Desktop\NBApredict-master\run\all.py", line 34, in <module>
    run_all()
  File "C:\Users\sergi\Desktop\NBApredict-master\run\all.py", line 26, in run_all
    predict.predict_all(db, session, year)
  File "C:\Users\sergi\Desktop\NBApredict-master\predict\predict.py", line 509, in predict_all
    odds_tbl = database.get_table_mappings("odds_{}".format(league_year))
  File "C:\Users\sergi\Desktop\NBApredict-master\database\database.py", line 70, in get_table_mappings
    self.metadata.reflect(self.engine, only=table_names)
  File "C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\schema.py", line 4259, in reflect
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///outputs//nba_db.db): (odds_2019)`

**Comment by Spencer-Weston** [comment]
Hi, sorry i'm just getting to this! Long story short, I'm doing a pretty significant reorganization of the project which should increase the usability and stability. That reorganization has it's own branch. And it'll be the first place you'll get a working version. In a few weeks, that branch should be up and running at which point I'll push it to the master branch.
